<div class="container">
    <div class="row">
        <div class="col-md-12 logo">
            <h1>
                Duck List <img src="/images/logo/logo-header.svg" alt="Duck List logo">
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
        <i class="fa-solid fa-list"></i>
            <h2>Créez plusieurs listes</h2>
        </div>
        <div class="col-md-4">
        <i class="fa-solid fa-list"></i>
            <h2>Définissez vos tâches</h2>
        </div>
        <div class="col-md-4">
        <i class="fa-solid fa-list"></i>
            <h2>Définissez l'importance</h2>
        </div>
    </div>
</div>