        <meta charset="UTF-8">
        <title>Duck List - To do list</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Application web de création de listes, suivi des tâches">
        <meta name="keywords" content="listes,tâches,importance,suivi">
        <meta name="author" content="Zanetti Jordan">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
        <link rel="stylesheet" type="text/css" href="/styles/bsmain.css">